/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/warehouse_shelving_3_low_poly.glb 
Author: THEAPPXR (https://sketchfab.com/oobexr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/warehouse-shelving-3-low-poly-73f84c4549354b15909e0f65cea4b18f
Title: WAREHOUSE SHELVING 3 LOW POLY
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/warehouse_shelving_3_low_poly.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Scaffalatura} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/warehouse_shelving_3_low_poly.glb')
